### ISSUE TITLE
Add mixer capability checks

### ISSUE THREAD

**Issue by emphasize** [OpenVoiceOS/ovos-PHAL-plugin-alsa#26]
Taken from a @goldyfruit matrix conversation 

deplovment method: docker
sound device: Google Voice HAT
```
2023-12-19 18:32:03.734 - PHAL - ovos_bus_client.session:from_message:471 - WARNING - No session context in message:mycroft.volume.get
2023-12-19 18:32:03.737 - PHAL - ovos_bus_client.session:from_message:472 - DEBUG - Update ovos-bus-client or add `session` to `message.context` where emitted. context={}
exception calling callback for <Future at 0x7fa61bff90 state=finished raised ALSAAudioError>
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_executor.py", line 57, in _callback
    self.emit("error", exc)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 118, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/ovos/.venv/lib/python3.11/site-packages/pyee/_base.py", line 88, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_alsa/__init__.py", line 113, in handle_volume_request
    "muted": self.alsa.is_muted()}))
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_PHAL_plugin_alsa/__init__.py", line 223, in is_muted
    return bool(self.mixer.getmute()[0])
                ^^^^^^^^^^^^^^^^^^^^
alsaaudio.ALSAAudioError: Mixer Master,0 has no playback switch capabilities, [default]
```

Add capability checks to prevent this behaviour

**Comment by goldyfruit** [comment]
:+1:
